### PR TITLE
Open filename found in argument

### LINKED ISSUE #50: bug when drag and drop xml file onto exe
When I drag an xml onto randoTracker.exe in the file system I get the "+ open with randoTracker" but when i drop it opens randoTracker with the last xml i had open loaded not the one that i dropped on it.

### PR DESCRIPTION
**Pull request by Carouelle**
Closes #50

### CODE REVIEW

**Comment by Datyedyeguy** [comment]
Should probably still try to load & initialize the IP/Port/cboCompression.SelectedIndex from the randoSettings file, but looks clean as far as taking the xml to load from the command line.

**Comment by Carouelle** [comment]
Sounds fair, should have looked a bit more around parts I intend to skip :+1:

**Comment by Carouelle** [comment]
Disregard my latest commit, tired and pushed while compiling :(

**Comment by Carouelle** [comment]
I moved to check the command argument after loading the settings file, since what we get from the argument should be prefered as the `gameFile`

**Pull request merged**
